services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: api_development
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/front
    ports:
      - 3001:3001
    depends_on:
      - backend
    tty: true
    stdin_open: true
  
volumes:
  mysql_data:
