name: CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      SECRET_KEY_BASE: dummy_secret
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_password

    services:
      db:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: test_password
        ports:
          - 3306:3306

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install
      
      - name: Brakeman
        run: |
          bundle update brakeman
          bin/brakeman --no-pager

      - name: RuboCop
        run: bundle exec rubocop

      - name: Set up database
        run: bin/rails db:create db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec

  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Build
        run: npm run build